# Generated by Django 3.1.2 on 2020-12-04 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clima', '0002_pronosticopasado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pronostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
                ('temp_max', models.IntegerField()),
                ('temp_min', models.IntegerField()),
                ('descripcion', models.CharField(max_length=150)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clima.ciudad')),
            ],
        ),
        migrations.DeleteModel(
            name='PronosticoPasado',
        ),
    ]
